"""The monolithic MILP reference. REQUIRES CPLEX; ~10 s.

WHY THIS FILE EXISTS. Spec non-negotiable 8 requires that a reported lower bound be
checked against a feasible objective "sourced from an independent MILP rather than from
a Benders run of this same code, which is what made the previous 4190.74 circular"
(D30). That objective is 4183.24, and for months the code producing it was NOT in the
repository -- `aux_py/` was empty and every occurrence of the number was prose or a
hardcoded constant. The check could not be regenerated and its independence could not be
inspected. The MILP is back (D50) and this file is what stops it going missing again:
if `src/mobauto2_milp/` is deleted, moved, or broken, the suite says so.

WHAT "INDEPENDENT" MEANS HERE, precisely. The monolith attaches the exact recourse LP
and pins theta to it by EQUALITY, so there is no cut and no theta approximation -- the
whole D30 defect class cannot reach it. That is independence from the DECOMPOSITION.
It is not independence from the FORMULATION: `mobauto2_milp/model.py` is a second copy
of the first-stage model that `mobauto2_benders/problem/master_impl.py` also implements.
A defect present in both copies is invisible to this check. Cite 4183.24 that way.

Run just these:
    python -m unittest tests.test_monolith_reference -v
"""

from __future__ import annotations

import unittest
from pathlib import Path

import _helpers  # noqa: F401  (puts src/ on sys.path)
from _helpers import CONFIGS, fixture_for_backend, require_solver_backend

MONOLITH_CONFIG = CONFIGS / "milp" / "baseline_d9_monolith.yaml"
BENDERS_CONFIG = CONFIGS / "baseline_d9.yaml"

# The reference. Regenerated by MONOLITH_CONFIG, not copied from a Benders run.
BASELINE_D9_OPTIMUM = 4183.24


class TestTheMonolithIsPresent(unittest.TestCase):
    """No solver needed. These fail loudly if the reference instrument disappears."""

    def test_the_package_is_importable(self):
        import mobauto2_milp.monolith  # noqa: F401
        import mobauto2_milp.model  # noqa: F401

    def test_the_regenerating_config_exists(self):
        self.assertTrue(
            MONOLITH_CONFIG.exists(),
            f"{MONOLITH_CONFIG} is missing; 4183.24 would again be a number with no "
            "reproducible source, which is the state D50 found and fixed",
        )

    def test_the_two_configs_describe_the_same_instance(self):
        """The reference is only a reference if it prices the SAME problem.

        Without this the two files could drift -- a different Q, horizon, penalty or
        fleet on either side -- and 4183.24 would quietly stop being the optimum of
        the instance the Benders tests check against, with nothing reporting it.
        """
        from mobauto2_benders.config import load_config as load_benders
        from mobauto2_milp.config import load_config as load_milp

        b = load_benders(BENDERS_CONFIG)
        m = load_milp(MONOLITH_CONFIG)

        self.assertEqual(b.model.time.T_minutes, m.model.time.T_minutes)
        self.assertEqual(b.model.time.slot_resolution, m.model.time.slot_resolution)
        self.assertEqual(
            b.model.time.trip_duration_minutes, m.model.time.trip_duration_minutes
        )
        self.assertEqual(b.model.fleet.Q, m.model.fleet.Q)
        self.assertEqual(b.model.energy.Emax, m.model.energy.Emax)
        self.assertEqual(b.model.energy.L, m.model.energy.L)
        self.assertAlmostEqual(
            float(b.model.costs.start_cost_epsilon),
            float(m.model.costs.start_cost_epsilon),
            places=9,
        )
        self.assertAlmostEqual(
            float(b.model.costs.concurrency_penalty),
            float(m.model.costs.concurrency_penalty),
            places=9,
        )

    def test_the_penalty_and_seats_agree(self):
        """`p` is in slot units on both sides (D7/D8/D50), so equal `p` at equal
        slot_resolution is equal policy. Checked separately because the two configs
        keep it under different section names."""
        from mobauto2_benders.config import load_config as load_benders
        from mobauto2_milp.config import load_config as load_milp

        b = load_benders(BENDERS_CONFIG)
        m = load_milp(MONOLITH_CONFIG)
        self.assertAlmostEqual(float(b.subproblem.S), float(m.service.S), places=9)
        self.assertAlmostEqual(float(b.subproblem.p), float(m.service.p), places=9)
        self.assertEqual(b.subproblem.Wmax_minutes, m.service.Wmax_minutes)


class TestTheReferenceIsRegenerable(unittest.TestCase):
    """REQUIRES AN LP/MIP BACKEND. ~7 s."""

    @classmethod
    def setUpClass(cls):
        require_solver_backend()
        from mobauto2_milp.config import load_config
        from mobauto2_milp.app import _prepare_params
        from mobauto2_milp.model import MobautoMilpModel
        from mobauto2_milp.monolith import MonolithSolver

        cfg = load_config(fixture_for_backend(MONOLITH_CONFIG))
        mp, sp = _prepare_params(cfg, {})
        cls.solver = MonolithSolver(MobautoMilpModel, cfg, mp, sp)
        cls.result = cls.solver.run()

    def test_it_reproduces_the_reference_optimum(self):
        self.assertAlmostEqual(
            float(self.result.best_upper_bound), BASELINE_D9_OPTIMUM, places=2
        )

    def test_it_proves_optimality_rather_than_stopping_on_the_clock(self):
        """A clock-truncated MIP is machine-dependent (D26). A reference produced that
        way would be a different number on every machine, so the run must terminate on
        the gap."""
        from mobauto2_milp.types import SolveStatus

        self.assertEqual(self.result.status, SolveStatus.OPTIMAL)
        self.assertAlmostEqual(
            float(self.result.best_lower_bound), BASELINE_D9_OPTIMUM, places=2
        )

    def test_the_relaxed_occupancy_variables_come_out_integral(self):
        """`atL`, `atM` and `inTrip` are continuous [0,1] here and Binary in the
        Benders master. That is only safe because each is pinned by an equality driven
        by binary `y` from a fixed initial state, so integrality is implied rather than
        imposed. Verified, not assumed: if it ever stops holding, the monolith is
        solving a RELAXATION and its objective is a lower bound, not the optimum --
        which would invert the meaning of the `LB <= 4183.24` check everywhere.
        """
        import pyomo.environ as pyo

        m = self.solver.master.m
        for name in ("atL", "atM", "inTrip"):
            var = getattr(m, name)
            worst = 0.0
            for idx in var:
                v = pyo.value(var[idx], exception=False)
                if v is not None:
                    worst = max(worst, abs(float(v) - round(float(v))))
            with self.subTest(variable=name):
                self.assertLess(
                    worst,
                    1e-6,
                    f"{name} came back fractional (max deviation {worst:.3e}); the "
                    "monolith is solving a relaxation of the Benders master",
                )


if __name__ == "__main__":
    unittest.main()
