"""Generate a diverse demand set for the multi-resolution measurements.

    python scripts/make_instances.py [--out setups/generated]

WHAT IS VARIED, AND WHY THIS AND NOT SOMETHING ELSE. The result under test is that slot
aggregation misjudges WHO IS REACHABLE inside a wait cap, so the dimension that should
drive it is the TEMPORAL STRUCTURE of demand -- how much of it lives at a finer grain than
one slot. Total volume, fleet size and horizon are held fixed here so the profiles differ
in shape alone; fleet and slot width are swept separately by the runner, which keeps each
sweep one-dimensional.

The shapes, in rough order of how much sub-slot structure they carry:

  flat      arrivals spread uniformly across the horizon. Sub-slot position is close to
            uniform inside every slot, so slot aggregation should lose the least here.
  commuter  one broad OUT peak in the morning, one broad RET peak in the evening. The
            classic shape, and the one the base instance resembles.
  bimodal   two narrower peaks per direction.
  burst     most of the demand inside a few short windows, each much narrower than a
            30-minute slot.
  spiky     many very short bursts scattered through the day.

PREDICTION, RECORDED BEFORE THE SWEEP RUNS. Minute-level valuation should buy least on
`flat` and most on `burst` and `spiky`, because that is where arrival times inside a slot
are most unevenly distributed and a slot-average is least like any individual passenger.
If the gain is flat across shapes, the mechanism is not what this file assumes it is.

SLOT ALIGNMENT IS AVOIDED ON PURPOSE. Structured shapes place their windows at minutes
congruent to 7 modulo 30, 15 and 10, and use spacings coprime with all three. The first
version did not, and produced a cell that measured the generator rather than the demand
(D54). An instance set for a resolution study must not be in phase with any resolution it
will be studied at.

Deterministic: a fixed seed per profile, so the set regenerates byte-identically.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

HORIZON_MIN = 660
N_PER_DIRECTION = 150


def _clip(t: int) -> int:
    return max(0, min(HORIZON_MIN - 1, int(t)))


def _flat(rng: random.Random, n: int, _dir: str) -> list[int]:
    return [rng.randrange(0, HORIZON_MIN) for _ in range(n)]


def _commuter(rng: random.Random, n: int, direction: str) -> list[int]:
    centre = 120 if direction == "OUT" else 520
    return [_clip(rng.gauss(centre, 90)) for _ in range(n)]


def _bimodal(rng: random.Random, n: int, direction: str) -> list[int]:
    a, b = (90, 300) if direction == "OUT" else (420, 580)
    return [
        _clip(rng.gauss(a if rng.random() < 0.5 else b, 40)) for _ in range(n)
    ]


def _burst(rng: random.Random, n: int, direction: str) -> list[int]:
    # Four windows of 12 minutes -- well under one 30-minute slot, so a slot average
    # is a poor description of any passenger in them.
    #
    # DELIBERATELY SLOT-MISALIGNED. The first version used starts 60/180/420, all exact
    # multiples of 30, which under the `start` convention put every departure exactly on
    # a burst and made slot reasoning accidentally correct -- the sweep then reported a
    # 0.00% gain that measured this generator's arithmetic, not burst demand (D54).
    # These starts are congruent to 7 modulo 30, 15 AND 10, so no resolution in the
    # sweep can align with them.
    starts = (67, 187, 427, 547) if direction == "OUT" else (157, 337, 487, 607)
    out: list[int] = []
    for i in range(n):
        s = starts[i % len(starts)]
        out.append(_clip(s + rng.randrange(0, 12)))
    return out


def _spiky(rng: random.Random, n: int, direction: str) -> list[int]:
    # Spacing 47 is coprime with 30, 15 and 10, so the spikes never settle into phase
    # with any slot grid the sweep uses; the offset keeps them off minute 0 as well.
    offset = 7 if direction == "OUT" else 23
    spikes = [offset + 47 * k for k in range(14)]
    out: list[int] = []
    for i in range(n):
        out.append(_clip(spikes[i % len(spikes)] + rng.randrange(0, 4)))
    return out


SHAPES = {
    "flat": _flat,
    "commuter": _commuter,
    "bimodal": _bimodal,
    "burst": _burst,
    "spiky": _spiky,
}


def build(shape: str, seed: int) -> str:
    rng = random.Random(seed)
    fn = SHAPES[shape]
    rows: list[tuple[str, int]] = []
    for direction in ("OUT", "RET"):
        for t in fn(rng, N_PER_DIRECTION, direction):
            rows.append((direction, int(t)))
    rows.sort(key=lambda r: (r[1], r[0]))
    lines = [
        f"# Generated by scripts/make_instances.py -- shape={shape}, seed={seed}.",
        "# Horizon 660 min, 150 requests per direction. Arrival times are MINUTES;",
        "# the slot models aggregate them at load and the minute pricer does not.",
        f"n: {len(rows)}",
        "requests:",
    ]
    for direction, t in rows:
        lines.append(f"- dir: {direction}")
        lines.append(f"  time: {t}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="setups/generated")
    args = ap.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for i, shape in enumerate(sorted(SHAPES)):
        path = out / f"{shape}.yaml"
        path.write_text(build(shape, seed=1000 + i), encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
